-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le :  mer. 23 déc. 2020 à 10:40
-- Version du serveur :  10.3.16-MariaDB
-- Version de PHP :  7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `ocblog`
--

-- --------------------------------------------------------

--
-- Structure de la table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `category` varchar(100) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `categories`
--

INSERT INTO `categories` (`id`, `category`, `slug`, `description`) VALUES
(1, 'Divers', 'divers', 'Catégorie par défaut'),
(4, 'Développement', 'developpemnt', 'Développement'),
(7, 'Actus', 'actus', 'Actualités'),
(8, 'Trucs et astuces', 'trucs-et-astuces', 'Trucs et astuces');

-- --------------------------------------------------------

--
-- Structure de la table `comments`
--

CREATE TABLE `comments` (
  `id` int(11) NOT NULL,
  `author` varchar(60) DEFAULT NULL,
  `comment` varchar(255) NOT NULL,
  `status` varchar(60) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `post_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `comments`
--

INSERT INTO `comments` (`id`, `author`, `comment`, `status`, `created_at`, `post_id`) VALUES
(1, '24', 'test', 'validated', '2020-12-23 10:31:12', 19),
(3, '24', 'vhvhv', 'validated', '2020-12-23 10:33:11', 32),
(4, '24', 'vhvhvccgcg', 'validated', '2020-12-23 10:33:14', 32),
(5, '24', 'vhvhv', 'validated', '2020-12-23 10:33:19', 32),
(6, '24', 'alert(&apos;toto&apos;)', 'validated', '2020-12-23 10:33:27', 32),
(7, '24', 'console.log(&apos;test&apos;)', 'validated', '2020-12-23 10:34:07', 45);

-- --------------------------------------------------------

--
-- Structure de la table `contacts`
--

CREATE TABLE `contacts` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `subject` text NOT NULL,
  `message` text NOT NULL,
  `status` varchar(20) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `contacts`
--

INSERT INTO `contacts` (`id`, `name`, `email`, `subject`, `message`, `status`, `created_at`) VALUES
(1, 'frederick agathe', 'fagathe77@gmail.com', 'Offre Intégrateur Web', 'tetfghbn', 'read', '2020-11-27 18:23:47'),
(2, 'frederick agathe', 'fagathe77@gmail.com', 'Offre Intégrateur Web', 'J&amp;#39;ai un projet à vous soumettre', 'read', '2020-11-27 18:23:47'),
(3, 'frederick agathe', 'fagathe77@gmail.com', 'Offre Intégrateur Web', 'J&amp;#39;ai un projet à vous soumettre', 'read', '2020-11-27 18:23:47'),
(4, 'frederick agathe', 'fagathe77@gmail.com', 'Offre Intégrateur Web', 'J&amp;#39;ai un projet à vous soumettre', 'read', '2020-11-27 18:23:47'),
(5, 'frederick agathe', 'fagathe77@gmail.com', 'Offre Intégrateur Web', 'J&amp;#39;ai un projet à vous soumettre', 'read', '2020-11-27 18:23:47'),
(6, 'Frédérick AGATHE', 'agathefrederick@gmail.com', 'Offre Intégrateur Web', 'J&apos;ai un super projet pour vous', 'pending', '2020-12-01 09:03:00'),
(7, 'Frédérick AGATHE', 'agathefrederick@gmail.com', 'Offre Intégrateur Web', 'Test message soutenance', 'pending', '2020-12-22 15:24:32');

-- --------------------------------------------------------

--
-- Structure de la table `posts`
--

CREATE TABLE `posts` (
  `id` int(11) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `writer` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `content` longtext DEFAULT NULL,
  `image` varchar(11) DEFAULT NULL,
  `slug` varchar(80) DEFAULT NULL,
  `chapo` text DEFAULT NULL,
  `status` varchar(60) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `posts`
--

INSERT INTO `posts` (`id`, `category_id`, `writer`, `title`, `content`, `image`, `slug`, `chapo`, `status`, `updated_at`, `created_at`) VALUES
(2, 1, '15', 'My second post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates assumenda, neque quam excepturi eum sequi perspiciatis ipsum at fugit modi atque eius quidem provident. Consequuntur consectetur cum eaque in rem iure ipsam repudiandae reiciendis quasi omnis eveniet obcaecati nostrum itaque eius error assumenda dolorem officia ipsa, quaerat exercitationem aspernatur saepe recusandae commodi. Eligendi doloremque similique tempora magnam cumque incidunt id hic, enim vel maiores consectetur earum in soluta vitae voluptas dolores. Ipsam doloribus ad nostrum officiis eaque itaque ab soluta ut cumque consequuntur natus provident est illum expedita accusamus exercitationem cum, temporibus excepturi deserunt atque. Consectetur corporis beatae recusandae modi.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vel ex voluptate, saepe neque totam, dolor, dolorem minima sit esse qui asperiores consequatur eos. Beatae, sapiente architecto esse nulla quia explicabo omnis ullam quam enim commodi accusantium facere aspernatur nam voluptates veniam officiis eum odio dolorem inventore libero? Quidem, commodi sequi cupiditate neque nisi asperiores qui fugit molestias? Dignissimos minima debitis dolore aut qui laboriosam repellat quas enim, nesciunt illum veritatis, architecto dolorem obcaecati possimus ipsum reiciendis illo ducimus ut, aliquam culpa. Eius asperiores totam quis delectus dolore tempora distinctio neque consequatur nam ullam aliquid explicabo recusandae optio, animi ipsam unde?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vitae laboriosam perspiciatis porro ullam. Impedit maxime quas, eaque provident tempore est odit dicta culpa quia facere sunt nihil perspiciatis vero placeat ut dolor autem incidunt facilis cupiditate repudiandae voluptatibus officiis? Commodi, maiores ipsam. Libero facere quaerat assumenda commodi ea nemo accusamus quos atque asperiores eum illo modi, exercitationem eius distinctio quidem placeat. Libero dolorem provident cumque pariatur est? Quas, minima animi doloribus laudantium labore vitae reiciendis illo fuga nesciunt corrupti vel necessitatibus adipisci praesentium blanditiis tempore consequuntur voluptatem facilis ab magni tempora cumque. Aliquam harum fugit, maiores at obcaecati autem hic!', '7', 'my-second-post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-12 15:11:29', '2020-10-31 11:13:31'),
(3, 1, '15', 'A random title', 'Lorem pisum', '5', 'mon-super-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-10 17:11:29', '2020-10-08 11:13:31'),
(6, 2, '20', 'My first post', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '6', 'article-non-defini', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-16 17:11:29', '0000-00-00 00:00:00'),
(12, 1, '16', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae.</p>\n<p><em>Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. </em></p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem <span style=\"text-decoration: underline;\">minima </span>dolor ducimus ad.</p>\n<p>Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>\n<p>&eacute;dite</p>\n<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'super-cheval', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:22', '2020-11-13 15:11:13'),
(13, 1, '20', 'titit ipsum', 'lorem ipsum', NULL, 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 08:11:20', '2020-11-17 08:11:20'),
(14, 1, '20', 'Titre de l\'article', '<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:01', '2020-11-17 11:11:52'),
(15, 1, '18', 'Article sur le sport', '<p><span style=\"text-decoration: underline;\"><em><strong>Titre de l\'article</strong></em></span></p>\n<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus voluptates iure reiciendis! Est, nulla. Maiores enim nisi quam cum repellat dolorem. Aut cupiditate assumenda quibusdam.</p>', '', 'article-sur-le-sport', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'draft', '2020-11-17 15:11:17', '2020-11-17 14:11:11'),
(16, 1, '16', 'titit', ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '14', 'titit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:19', '2020-11-17 15:11:05'),
(17, 1, '16', 'le cheval c\'est trop génial', '', '', 'le-cheval-c-est-trop-genial', '', 'draft', '2020-12-01 14:12:06', '2020-11-17 15:11:06'),
(18, 1, '20', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae.</p>\n<p>Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>\n<p>Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '15', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-30 03:11:59', '2020-11-17 15:11:00'),
(19, 4, '20', 'My first post', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '', 'article-par-defaut', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:15', '2020-11-17 15:11:40'),
(20, 4, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-09-16 17:11:29', '2020-10-22 11:13:31'),
(21, 4, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-02 04:09:28', '2020-10-22 11:13:31'),
(22, 4, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-10 17:11:29', '2020-10-22 11:13:31'),
(23, 4, '15', 'My second post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates assumenda, neque quam excepturi eum sequi perspiciatis ipsum at fugit modi atque eius quidem provident. Consequuntur consectetur cum eaque in rem iure ipsam repudiandae reiciendis quasi omnis eveniet obcaecati nostrum itaque eius error assumenda dolorem officia ipsa, quaerat exercitationem aspernatur saepe recusandae commodi. Eligendi doloremque similique tempora magnam cumque incidunt id hic, enim vel maiores consectetur earum in soluta vitae voluptas dolores. Ipsam doloribus ad nostrum officiis eaque itaque ab soluta ut cumque consequuntur natus provident est illum expedita accusamus exercitationem cum, temporibus excepturi deserunt atque. Consectetur corporis beatae recusandae modi.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vel ex voluptate, saepe neque totam, dolor, dolorem minima sit esse qui asperiores consequatur eos. Beatae, sapiente architecto esse nulla quia explicabo omnis ullam quam enim commodi accusantium facere aspernatur nam voluptates veniam officiis eum odio dolorem inventore libero? Quidem, commodi sequi cupiditate neque nisi asperiores qui fugit molestias? Dignissimos minima debitis dolore aut qui laboriosam repellat quas enim, nesciunt illum veritatis, architecto dolorem obcaecati possimus ipsum reiciendis illo ducimus ut, aliquam culpa. Eius asperiores totam quis delectus dolore tempora distinctio neque consequatur nam ullam aliquid explicabo recusandae optio, animi ipsam unde?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vitae laboriosam perspiciatis porro ullam. Impedit maxime quas, eaque provident tempore est odit dicta culpa quia facere sunt nihil perspiciatis vero placeat ut dolor autem incidunt facilis cupiditate repudiandae voluptatibus officiis? Commodi, maiores ipsam. Libero facere quaerat assumenda commodi ea nemo accusamus quos atque asperiores eum illo modi, exercitationem eius distinctio quidem placeat. Libero dolorem provident cumque pariatur est? Quas, minima animi doloribus laudantium labore vitae reiciendis illo fuga nesciunt corrupti vel necessitatibus adipisci praesentium blanditiis tempore consequuntur voluptatem facilis ab magni tempora cumque. Aliquam harum fugit, maiores at obcaecati autem hic!', '7', 'my-second-post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-12 15:11:29', '2020-10-31 11:13:31'),
(24, 1, '15', 'A random title', 'Lorem pisum', '5', 'mon-super-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-10 17:11:29', '2020-10-08 11:13:31'),
(25, 7, '20', 'My first post', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '6', 'article-non-defini', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-16 17:11:29', '0000-00-00 00:00:00'),
(26, 4, '16', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae.</p>\n<p><em>Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. </em></p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem <span style=\"text-decoration: underline;\">minima </span>dolor ducimus ad.</p>\n<p>Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>\n<p>&eacute;dite</p>\n<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'super-cheval', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:22', '2020-11-13 15:11:13'),
(27, 1, '20', 'titit ipsum', 'lorem ipsum', NULL, 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 08:11:20', '2020-11-17 08:11:20'),
(28, 7, '20', 'Titre de l\'article', '<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:01', '2020-11-17 11:11:52'),
(29, 8, '18', 'Article sur le sport', '<p><span style=\"text-decoration: underline;\"><em><strong>Titre de l\'article</strong></em></span></p>\n<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus voluptates iure reiciendis! Est, nulla. Maiores enim nisi quam cum repellat dolorem. Aut cupiditate assumenda quibusdam.</p>', '', 'article-sur-le-sport', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'draft', '2020-11-17 15:11:17', '2020-11-17 14:11:11'),
(30, 8, '16', 'titit', ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '14', 'titit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:19', '2020-11-17 15:11:05'),
(31, 4, '16', 'titit', '<p>jkjui</p>\n<p>njhjn,</p>\n<p>&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>\n<p>&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>', '', 'titit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:06', '2020-11-17 15:11:06'),
(32, 4, '20', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '15', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 17:11:42', '2020-11-17 15:11:00'),
(33, 8, '20', 'My first post', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '', 'article-par-defaut', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:15', '2020-11-17 15:11:40'),
(34, 7, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-10-16 17:11:29', '2020-10-22 11:13:31'),
(35, 1, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-04-16 17:11:29', '2020-10-22 11:13:31'),
(36, 4, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-07 17:11:29', '2020-10-22 11:13:31'),
(37, 4, '15', 'My second post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates assumenda, neque quam excepturi eum sequi perspiciatis ipsum at fugit modi atque eius quidem provident. Consequuntur consectetur cum eaque in rem iure ipsam repudiandae reiciendis quasi omnis eveniet obcaecati nostrum itaque eius error assumenda dolorem officia ipsa, quaerat exercitationem aspernatur saepe recusandae commodi. Eligendi doloremque similique tempora magnam cumque incidunt id hic, enim vel maiores consectetur earum in soluta vitae voluptas dolores. Ipsam doloribus ad nostrum officiis eaque itaque ab soluta ut cumque consequuntur natus provident est illum expedita accusamus exercitationem cum, temporibus excepturi deserunt atque. Consectetur corporis beatae recusandae modi.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vel ex voluptate, saepe neque totam, dolor, dolorem minima sit esse qui asperiores consequatur eos. Beatae, sapiente architecto esse nulla quia explicabo omnis ullam quam enim commodi accusantium facere aspernatur nam voluptates veniam officiis eum odio dolorem inventore libero? Quidem, commodi sequi cupiditate neque nisi asperiores qui fugit molestias? Dignissimos minima debitis dolore aut qui laboriosam repellat quas enim, nesciunt illum veritatis, architecto dolorem obcaecati possimus ipsum reiciendis illo ducimus ut, aliquam culpa. Eius asperiores totam quis delectus dolore tempora distinctio neque consequatur nam ullam aliquid explicabo recusandae optio, animi ipsam unde?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vitae laboriosam perspiciatis porro ullam. Impedit maxime quas, eaque provident tempore est odit dicta culpa quia facere sunt nihil perspiciatis vero placeat ut dolor autem incidunt facilis cupiditate repudiandae voluptatibus officiis? Commodi, maiores ipsam. Libero facere quaerat assumenda commodi ea nemo accusamus quos atque asperiores eum illo modi, exercitationem eius distinctio quidem placeat. Libero dolorem provident cumque pariatur est? Quas, minima animi doloribus laudantium labore vitae reiciendis illo fuga nesciunt corrupti vel necessitatibus adipisci praesentium blanditiis tempore consequuntur voluptatem facilis ab magni tempora cumque. Aliquam harum fugit, maiores at obcaecati autem hic!', '7', 'my-second-post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-12 15:11:29', '2020-10-31 11:13:31'),
(38, 1, '15', 'A random title', 'Lorem pisum', '5', 'mon-super-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-10 17:11:29', '2020-10-08 11:13:31'),
(39, 7, '20', 'My first post', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '6', 'article-non-defini', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-16 17:11:29', '0000-00-00 00:00:00'),
(40, 4, '16', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae.</p>\n<p><em>Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. </em></p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem <span style=\"text-decoration: underline;\">minima </span>dolor ducimus ad.</p>\n<p>Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>\n<p>&eacute;dite</p>\n<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'super-cheval', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:22', '2020-11-13 15:11:13'),
(41, 1, '20', 'titit ipsum', 'lorem ipsum', NULL, 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 08:11:20', '2020-11-17 08:11:20'),
(42, 7, '20', 'Titre de l\'article', '<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:01', '2020-11-17 11:11:52'),
(43, 8, '18', 'Article sur le sport', '<p><span style=\"text-decoration: underline;\"><em><strong>Titre de l\'article</strong></em></span></p>\n<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus voluptates iure reiciendis! Est, nulla. Maiores enim nisi quam cum repellat dolorem. Aut cupiditate assumenda quibusdam.</p>', '', 'article-sur-le-sport', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'draft', '2020-11-17 15:11:17', '2020-11-17 14:11:11'),
(44, 8, '16', 'titit', ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '14', 'titit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:19', '2020-11-17 15:11:05');
INSERT INTO `posts` (`id`, `category_id`, `writer`, `title`, `content`, `image`, `slug`, `chapo`, `status`, `updated_at`, `created_at`) VALUES
(45, 4, '16', 'titit', '<p>jkjui</p>\n<p>njhjn,</p>\n<p>&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>\n<p>&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>', '', 'titit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:06', '2020-11-17 15:11:06'),
(46, 4, '20', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '15', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 17:11:42', '2020-11-17 15:11:00'),
(47, 8, '20', 'My first post', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '', 'article-par-defaut', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:15', '2020-11-17 15:11:40'),
(48, 7, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-11 17:11:29', '2020-10-22 11:13:31'),
(49, 1, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-12 17:11:29', '2020-10-22 11:13:31'),
(50, 4, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-15 17:11:29', '2020-10-22 11:13:31'),
(51, 4, '15', 'My second post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates assumenda, neque quam excepturi eum sequi perspiciatis ipsum at fugit modi atque eius quidem provident. Consequuntur consectetur cum eaque in rem iure ipsam repudiandae reiciendis quasi omnis eveniet obcaecati nostrum itaque eius error assumenda dolorem officia ipsa, quaerat exercitationem aspernatur saepe recusandae commodi. Eligendi doloremque similique tempora magnam cumque incidunt id hic, enim vel maiores consectetur earum in soluta vitae voluptas dolores. Ipsam doloribus ad nostrum officiis eaque itaque ab soluta ut cumque consequuntur natus provident est illum expedita accusamus exercitationem cum, temporibus excepturi deserunt atque. Consectetur corporis beatae recusandae modi.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vel ex voluptate, saepe neque totam, dolor, dolorem minima sit esse qui asperiores consequatur eos. Beatae, sapiente architecto esse nulla quia explicabo omnis ullam quam enim commodi accusantium facere aspernatur nam voluptates veniam officiis eum odio dolorem inventore libero? Quidem, commodi sequi cupiditate neque nisi asperiores qui fugit molestias? Dignissimos minima debitis dolore aut qui laboriosam repellat quas enim, nesciunt illum veritatis, architecto dolorem obcaecati possimus ipsum reiciendis illo ducimus ut, aliquam culpa. Eius asperiores totam quis delectus dolore tempora distinctio neque consequatur nam ullam aliquid explicabo recusandae optio, animi ipsam unde?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Vitae laboriosam perspiciatis porro ullam. Impedit maxime quas, eaque provident tempore est odit dicta culpa quia facere sunt nihil perspiciatis vero placeat ut dolor autem incidunt facilis cupiditate repudiandae voluptatibus officiis? Commodi, maiores ipsam. Libero facere quaerat assumenda commodi ea nemo accusamus quos atque asperiores eum illo modi, exercitationem eius distinctio quidem placeat. Libero dolorem provident cumque pariatur est? Quas, minima animi doloribus laudantium labore vitae reiciendis illo fuga nesciunt corrupti vel necessitatibus adipisci praesentium blanditiis tempore consequuntur voluptatem facilis ab magni tempora cumque. Aliquam harum fugit, maiores at obcaecati autem hic!', '7', 'my-second-post', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-12 15:11:29', '2020-10-31 11:13:31'),
(52, 1, '15', 'A random title', 'Lorem pisum', '5', 'mon-super-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-10 17:11:29', '2020-10-08 11:13:31'),
(53, 7, '20', 'My first post', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '6', 'article-non-defini', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-16 17:11:29', '0000-00-00 00:00:00'),
(54, 4, '16', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae.</p>\n<p><em>Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis. </em></p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem <span style=\"text-decoration: underline;\">minima </span>dolor ducimus ad.</p>\n<p>Omnis qui eos blanditiis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>\n<p>&eacute;dite</p>\n<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'super-cheval', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:22', '2020-11-13 15:11:13'),
(55, 1, '20', 'titit ipsum', 'lorem ipsum', NULL, 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 08:11:20', '2020-11-17 08:11:20'),
(56, 7, '20', 'Titre de l\'article', '<p>Test de l\'&eacute;diteur de texte TinyMCE</p>', '', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 11:11:01', '2020-11-17 11:11:52'),
(57, 8, '18', 'Article sur le sport', '<p><span style=\"text-decoration: underline;\"><em><strong>Titre de l\'article</strong></em></span></p>\n<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellendus voluptates iure reiciendis! Est, nulla. Maiores enim nisi quam cum repellat dolorem. Aut cupiditate assumenda quibusdam.</p>', '', 'article-sur-le-sport', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'draft', '2020-11-17 15:11:17', '2020-11-17 14:11:11'),
(58, 8, '16', 'titit', ' Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.', '14', 'titit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:19', '2020-11-17 15:11:05'),
(59, 4, '16', 'titit', '<p>jkjui</p>\n<p>njhjn,</p>\n<p>&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>\n<p>&nbsp;Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis.</p>', '', 'titit', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:06', '2020-11-17 15:11:06'),
(60, 4, '20', 'Titre de l\'article', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '15', 'titre-de-l-article', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 17:11:42', '2020-11-17 15:11:00'),
(61, 8, '20', 'My first post', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>\n<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor quisquam doloremque incidunt perferendis aut! Totam alias sunt ullam dolor repellendus animi nostrum itaque facilis molestiae. Doloremque vero quam provident nihil veritatis, similique quod magni dolore deserunt optio, laboriosam perferendis * voluptatibus porro, dolorem minima dolor ducimus ad. Omnis qui eos blanditiis</p>', '', 'article-par-defaut', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-17 15:11:15', '2020-11-17 15:11:40'),
(62, 7, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-11-04 17:11:29', '2020-10-22 11:13:31'),
(63, 1, '20', 'titit ipsum 1', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo dolorum blanditiis adipisci hic. Quas ea, dignissimos delectus accusamus iure temporibus soluta consequuntur velit, possimus eaque excepturi accusantium sint porro iusto! Corrupti quasi qui maiores voluptate reiciendis perspiciatis iure facere distinctio earum sapiente minus enim deserunt explicabo quam quae laboriosam, neque dolores quidem possimus tenetur dolor quo eveniet molestiae. Error a porro eius natus facere repellendus voluptates, sed, saepe quam, neque explicabo labore architecto laborum ab aut unde pariatur magnam corporis odit. Quisquam amet repudiandae, minus aliquid, perferendis, vero soluta impedit nemo doloremque sequi minima est? Quasi, corporis inventore ab ad reprehenderit voluptatibus illum doloribus aliquam provident, eaque nulla excepturi incidunt. Ducimus, accusantium voluptate adipisci temporibus reprehenderit labore unde ipsam necessitatibus aliquam. Debitis nam, accusantium fugiat quam placeat unde nulla cupiditate hic itaque repellat, esse officiis? Perspiciatis rem dolor qui laboriosam cupiditate quasi, quod placeat molestias minus, quisquam consequatur cumque rerum repudiandae quia odio. Nihil quibusdam laborum laboriosam voluptate exercitationem perspiciatis suscipit eum aut autem doloremque sed libero, dicta quisquam quos maiores, rerum aspernatur. Animi suscipit alias vero sit, laboriosam ut vel unde odit modi quae tempore sapiente voluptatem tempora nihil assumenda fugit atque? Architecto veritatis iure nisi? Illum eaque, quo praesentium quia facere illo? Veritatis, necessitatibus provident beatae, sint error inventore sunt magnam, doloribus cum deserunt quo. Amet aspernatur aliquam nisi laboriosam delectus? Dignissimos expedita veritatis qui, alias aut pariatur et dolore adipisci, totam saepe id laboriosam libero numquam. Provident soluta quibusdam rerum tempora doloribus perspiciatis et velit, earum impedit expedita nemo laudantium debitis cupiditate eligendi in beatae id culpa illum nobis itaque ipsum tenetur aspernatur nihil ex? Corporis amet necessitatibus inventore, vitae, laudantium ipsa eos ea officiis enim dolorem voluptas libero voluptatibus cum culpa veniam nulla repellendus placeat iste non nihil aliquid. Quod obcaecati eveniet similique dolor sit tenetur.', '4', 'titit-ipsum', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta iusto doloremque magni est officiis adipisci sunt nostrum ipsum voluptates?', 'published', '2020-02-16 17:11:29', '2020-10-22 11:13:31'),
(64, 1, '16', 'le cheval c&apos;est trop génial', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ratione molestias eligendi amet aspernatur, nihil numquam quisquam autem similique tempore odit alias et illo dolorum tempora laudantium facilis! Facere, deleniti unde voluptatum praesentium illum cupiditate?\r\nLorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ratione molestias eligendi amet aspernatur, nihil numquam quisquam autem similique tempore odit alias et illo dolorum tempora laudantium facilis! Facere, deleniti unde voluptatum praesentium illum cupiditate?\r\n&amp;nbsp;', '27', 'le-cheval-c-est-trop-genial', '', 'draft', '2020-12-09 11:12:41', '2020-12-09 11:12:41'),
(65, 1, '16', 'le cheval c\'est trop génial', '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ratione molestias eligendi amet aspernatur, nihil numquam quisquam autem similique tempore odit alias et illo dolorum tempora laudantium facilis! Facere, deleniti unde voluptatum praesentium illum cupiditate? Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam ratione molestias eligendi amet aspernatur, nihil numquam quisquam autem similique tempore odit alias et illo dolorum tempora laudantium facilis! Facere, deleniti unde voluptatum praesentium illum cupiditate? &nbsp;</p>', '', 'le-cheval-c-est-trop-genial', '', 'draft', '2020-12-09 11:12:12', '2020-12-09 11:12:12');

-- --------------------------------------------------------

--
-- Structure de la table `uploads`
--

CREATE TABLE `uploads` (
  `id` int(11) NOT NULL,
  `path` varchar(100) DEFAULT NULL,
  `type` varchar(60) DEFAULT NULL,
  `created_at` varchar(60) DEFAULT NULL,
  `users_id` int(11) NOT NULL,
  `posts_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `uploads`
--

INSERT INTO `uploads` (`id`, `path`, `type`, `created_at`, `users_id`, `posts_id`) VALUES
(4, 'uploads/post/gSYIqe3oH45WQnvOaJGVuzExR0BLwi.jpg', 'poster', '13-11-2020 10:11', 0, 1),
(5, 'uploads/post/NWEfbe5nV4qFTOZw3LLdzjICiMh6ol.jpg', 'poster', '13-11-2020 à 00:11', 0, 3),
(6, 'uploads/post/pY9IhDvVOLKBeXA7RSlEWNZ2FHws8f.jpg', 'poster', '13-11-2020 à 00:11', 0, 6),
(7, 'uploads/post/LwPcAtFLrYkhCDTqSxe9NV72iy3o5p.jpg', 'poster', '13-11-2020 12:11', 0, 2),
(8, 'uploads/post/tVqiX04Qjs2UTKcBLSD1rRw8LNhZ75.jpg', 'poster', '13-11-2020 09:11', 0, 7),
(9, 'uploads/post/8jQF5IkM1zhUgLbnwy26Xq4RBDi9Ax.jpg', 'poster', '13-11-2020 15:11:55', 0, 9),
(10, 'uploads/post/LDldni5OjFuGEkWR9NULAbQpJ6SsrM.jpg', 'poster', '13-11-2020 15:11:07', 0, 10),
(11, 'uploads/post/tNiE2VrKR5Cxc1Ae8PfWkTjlGZswFd.jpg', 'poster', '13-11-2020 15:11:20', 0, 11),
(12, 'uploads/post/sGLeRyo93YqwFS5cu4PrUA6baL0JTH.jpg', 'poster', '2020-11-17 08:11:20', 0, 12),
(13, 'uploads/post/0SRp1X6TvQhA9nNK8bgsejyqoHDdML.jpg', 'poster', '2020-11-17 14:11:11', 0, 15),
(14, 'uploads/post/b0lrwDs4Mf72JIAuCNScjBepodPGOW.jpg', 'poster', '2020-11-17 15:11:19', 0, 16),
(15, 'uploads/post/WVaHcIZhPlyEeLOUtsDAYpK8GJo4NR.jpg', 'poster', '2020-11-17 17:11:26', 0, 18),
(16, 'uploads/post/ZpLgkz9v0EcHP6Ubt28usdf4FLSAWK.jpg', 'poster', '2020-11-17 15:11:14', 0, 19),
(18, 'uploads/user/6BOTe9krQVlyHPCXzdM80KobLNI7np.jpg', 'profile', '2020-11-26 14:11:54', 20, 0),
(24, 'uploads/user/aKykeDbvfTzLqXI7gciFlLMBZO4w8o.jpg', 'profile', '2020-11-26 18:11:56', 21, 0),
(25, 'uploads/user/FBnrQlzdwZDoLpcjR2b4eNsXuKE801.png', 'profile', '2020-12-01 00:12:46', 17, 0),
(26, 'uploads/user/whCpi9sTYR10z8FyLVvEJgeW2XQDoH.jpg', 'profile', '2020-12-09 10:12:23', 24, 0),
(27, 'uploads/post/AbUJB2HTi4zwRhoM7njQk1qS0LKYlP.jpg', 'poster', '2020-12-09 11:12:41', 0, 64),
(28, 'uploads/post/LjPv6THyEx14OIhoipe5a2bS7DQGlN.jpg', 'profile', '2020-12-09 12:12:13', 0, 66),
(29, 'uploads/post/EOqXn8Lszlp9PWb0cDyHL1auFtieKv.png', 'profile', '2020-12-22 15:12:47', 0, 67);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `pseudo` varchar(60) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `chapo` text DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `image` int(11) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `confirm` varchar(20) DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  `role` varchar(60) NOT NULL,
  `last_connection` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `gender`, `firstname`, `lastname`, `pseudo`, `email`, `chapo`, `position`, `image`, `password`, `slug`, `confirm`, `token`, `role`, `last_connection`, `created_at`) VALUES
(15, NULL, 'Frederic', 'Agathe', 'fredsko77', 'agathefrederick@gmail.com', 'Je suis un super blogueur.', NULL, NULL, '$argon2i$v=19$m=1024,t=2,p=2$NlhycmxoVnpyaGJLbkY4Ng$s12sZLpiUYcs+YBzV1QjPE/i0Ml5USx4bxYWJtbFIds', NULL, '1', 'WLU7xrFAeC1wVfgbkScGX8vDRBpT4OQ92hoIELqynHjYPN3sltMzu0d6i5JZaK202012222132455928091', 'user', '2020-12-22 13:55:24', '2020-11-06 17:15:48'),
(16, NULL, 'Jeremie', 'Dupond', 'monkey d luffy', 'j.dupond@mail.de', NULL, NULL, NULL, '$argon2i$v=19$m=1024,t=2,p=2$MmJjek0ucDYvQlhrVlNTag$u6DZsWmGUvUWuS7S14EHVP1e/9mXs+1C0h6mNOjzFGM', NULL, '1', 'ZTUa1KFY03g546q9ketyIVPQDsXC2wdBMcJjulSboiRxNL8n7fHEhGWpLArzvO20201110123521306401', 'admin', '2020-11-10 09:41:13', '2020-11-10 09:34:32'),
(17, NULL, 'Toto', 'Jambo', 'fredsko77', 'toto@mail.fr', 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reiciendis consequuntur molestiae similique facere maiores ipsam porro! Explicabo nemo doloribus tempora ipsa eos, inventore aliquid distinction.', NULL, 25, '$argon2i$v=19$m=1024,t=2,p=2$QWVQMzZwVERpYjc0MllDZw$YAqE6N2oelZcssPjoLx7RxNXHARa7E0gFYGbmx7ckgA', NULL, '1', 'Ug7BIYh8xiqG1j4DzCAPyorMFpltSV3Nf6RLkKXbdeOuZQEWTas5w90cL2vHnJ202012201113136753897', 'user', '2020-12-01 11:36:31', '2020-11-10 12:05:14'),
(18, NULL, 'jean-pierre', 'Simon', 'sacha', 'toto@mail.com', NULL, NULL, NULL, '$argon2i$v=19$m=1024,t=2,p=2$MVVuS0oxbEtRM2pMTkxKVw$BFUapit+FXcTWbqCZYhTU0JRHvRtiF7UvOR1CtHfHNY', NULL, '1', 'MWjTzdQ9AoOFs8kXch5VpgSU1ByrN0tq6uKiYf72HILvwRJxbElDeCPG3aL4nZ20201110125419704101', 'admin', NULL, '2020-11-10 12:06:56'),
(19, NULL, 'tom', 'jerry', 'kilua', 'tom-jerry@mail.fr', NULL, NULL, NULL, '$argon2i$v=19$m=1024,t=2,p=2$Zm1ZTHBiYmd5anV0bC9zWg$NOi4hg5wEuyElUuaYVNfe9J4WZG3pMC3cuQ9dvF8z8g', NULL, '1', 'Qapw3VFxqbHUEGlB5S9ys8gdvXuLRrJ7jkOz6L2TZt0cN1nCYKDPA4fMiIheWo202011116234443082620', 'user', '2020-11-16 23:43:44', '2020-11-16 23:42:59'),
(20, NULL, 'frederick', 'agathe', 'uchiha', 'fagathe77@gmail.com', 'Lorem ipsum dolor sit amet consectetur&comma; adipisicing elit&period; Corporis expedita voluptatibus veritatis praesentium soluta perspiciatis repellat consequatur.', 'D&eacute;veloppeur d\'application Web PHP&sol;Symfony', 18, '$argon2i$v=19$m=1024,t=2,p=2$R1JUNVBDcVpKa1c5VjIvNA$XMnV/G/d2f7/7nUt7sxfMSwfCInASxyYo5UxWOSOoeo', NULL, '1', 'qyvRarplPJfSuzGtb6COw7YjWNToFU108ViceLEhM29ZkXs4AIQL3xd5KnBHgD202012511102210065356', 'admin', '2020-12-11 10:10:22', '2020-11-22 17:34:25'),
(23, 'mr', 'Test', 'User', NULL, 'test@mail.fr', NULL, NULL, NULL, '$argon2i$v=19$m=1024,t=2,p=2$dkZVSE8zY1pTNFdEamg3Uw$FOixGX2iBIQvmUoW5lNnT7yELG0mN4OH5UPMePXKZUg', 'test-user', '1', 'lhwIBqYv21stXTxRErNpdKL6Zf9ajWMbHUL3kA5GVSPuDziogOn4eF08C7yQJc202012511105520972325', 'user', '2020-12-11 10:20:55', '2020-12-02 17:13:52'),
(24, 'mr', 'Admin', 'User', 'fredsko77', 'admin@mail.com', '', 'Développeur d\'application Web PHP/Symfony', 26, '$argon2i$v=19$m=1024,t=2,p=2$dWlTVEJnTTRzU0F4Ukxuaw$knW2MKa8Xe2haRjawX861ZllJ6ghSEvL5Go/Me60m68', 'admin-user', '1', 'GquPAMeNYhcVUl0sKWdIjfZi3XS4xBrnvtE8OTLwF25zCLHQDa6bRgokJp71y9202012323100531378241', 'admin', '2020-12-23 10:31:05', '2020-12-02 17:25:01');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id` (`id`);

--
-- Index pour la table `comments`
--
ALTER TABLE `comments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `post_id` (`post_id`),
  ADD KEY `id` (`id`);

--
-- Index pour la table `contacts`
--
ALTER TABLE `contacts`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id` (`id`);

--
-- Index pour la table `uploads`
--
ALTER TABLE `uploads`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

--
-- AUTO_INCREMENT pour la table `comments`
--
ALTER TABLE `comments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT pour la table `contacts`
--
ALTER TABLE `contacts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT pour la table `uploads`
--
ALTER TABLE `uploads`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `comments`
--
ALTER TABLE `comments`
  ADD CONSTRAINT `comments_ibfk_1` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
